export function generateUserData(count = 1000) {
    const users = [];
    const names = [
      'John Doe', 'Jane Smith', 'Michael Johnson', 'Sarah Williams',
      'Emily Parker', 'Samuel Garcia', 'Lisa Green', 'Anthony Hernandez',
      'Nicole Johnson', 'Matthew Wilson', 'Jessica Adams', 'Joshua Brown',
      'Emma Lee', 'Olivia White', 'Alexander Davis', 'Sophia Martinez',
      'William Turner', 'Mason Carter', 'Charlotte King', 'Jacob Thomas',
      'Ethan Phillips', 'Amelia Campbell', 'Mia Walker', 'Daniel Rogers',
      'Liam Lewis', 'Noah Roberts', 'Isabella Thompson', 'Zoe Gonzalez',
      'Oliver Wilson', 'Harper Hill', 'Michael Baker', 'Ava Bennett',
      'Lucas Nelson', 'Sophia Garcia', 'James Green', 'Ella Flores',
      'Ethan Richardson', 'Victoria Carter', 'Alexander Rodriguez', 'Mia Cox',
      'Christopher Mitchell', 'Grace Foster', 'David Peterson', 'Madison Bailey',
      'John Parker', 'Chloe Cooper', 'Henry Clark', 'Lily Bailey',
      'Michael Thomas', 'Emma Anderson', 'Jacob White', 'Ava Young',
      'Olivia Moore', 'Matthew Lewis', 'Charlotte King', 'Jackson Harris',
      'Emily Clark', 'David Hill', 'Lucas Wright', 'Sophia Baker',
      'Liam Adams', 'Ava Reed', 'Mason Perry', 'Chloe Morris',
      'Isabella Foster', 'Benjamin James', 'Olivia Wilson', 'James Roberts',
      'Sophia Walker', 'Mia Hill', 'Jacob Scott', 'Amelia Lewis',
      'Chloe Parker', 'Benjamin Phillips', 'William Allen', 'Harper King',
      'Noah Baker', 'Isabella Bailey', 'Mason Carter', 'Amelia Reed',
      'Emma Rodriguez', 'Joshua Sanchez', 'Madison Hill', 'William Brown',
      'Lucas Smith', 'Grace White', 'Ava Jackson', 'David Wilson',
      'James Adams', 'Emma Turner', 'Noah Thompson', 'Sophia Davis',
      'Michael Roberts', 'Chloe Taylor', 'James Lewis', 'Amelia Allen',
      'William Gonzalez', 'Harper Harris', 'Jacob Turner', 'Grace Adams',
      'Mia Mitchell', 'Lucas Wilson', 'Olivia Smith', 'Sophia Thomas',
      'Emma Johnson', 'Charlotte Wilson', 'William Moore', 'Benjamin Hill',
      'Harper Garcia', 'Sophia Smith', 'Ava Brown', 'James Martinez'
    ];
    const emails = [
      'john@example.com', 'jane@example.com', 'michael@example.com', 'sarah@example.com',
      'emily@example.com', 'samuel@example.com', 'lisa@example.com', 'anthony@example.com',
      'nicole@example.com', 'matthew@example.com', 'jessica@example.com', 'joshua@example.com',
      'emma@example.com', 'olivia@example.com', 'alexander@example.com', 'sophia@example.com',
      'william@example.com', 'mason@example.com', 'charlotte@example.com', 'jacob@example.com',
      'ethan@example.com', 'amelia@example.com', 'mia@example.com', 'daniel@example.com',
      'liam@example.com', 'noah@example.com', 'isabella@example.com', 'zoe@example.com',
      'oliver@example.com', 'harper@example.com', 'michael@example.com', 'ava@example.com',
      'lucas@example.com', 'sophia@example.com', 'james@example.com', 'ella@example.com',
      'ethan@example.com', 'victoria@example.com', 'alexander@example.com', 'mia@example.com',
      'christopher@example.com', 'grace@example.com', 'david@example.com', 'madison@example.com',
      'john@example.com', 'chloe@example.com', 'henry@example.com', 'lily@example.com',
      'michael@example.com', 'emma@example.com', 'jacob@example.com', 'ava@example.com',
      'olivia@example.com', 'matthew@example.com', 'charlotte@example.com', 'jackson@example.com',
      'emily@example.com', 'david@example.com', 'lucas@example.com', 'sophia@example.com',
      'liam@example.com', 'ava@example.com', 'mason@example.com', 'chloe@example.com',
      'isabella@example.com', 'benjamin@example.com', 'olivia@example.com', 'james@example.com',
      'sophia@example.com', 'mia@example.com', 'jacob@example.com', 'amelia@example.com',
      'chloe@example.com', 'benjamin@example.com', 'william@example.com', 'harper@example.com',
      'noah@example.com', 'isabella@example.com', 'mason@example.com', 'amelia@example.com',
      'emma@example.com', 'joshua@example.com', 'madison@example.com', 'william@example.com',
      'lucas@example.com', 'grace@example.com', 'ava@example.com', 'david@example.com',
      'james@example.com', 'emma@example.com', 'noah@example.com', 'sophia@example.com',
      'michael@example.com', 'chloe@example.com', 'james@example.com', 'amelia@example.com',
      'william@example.com', 'harper@example.com', 'jacob@example.com', 'grace@example.com',
      'mia@example.com', 'lucas@example.com', 'olivia@example.com', 'sophia@example.com',
      'emma@example.com', 'charlotte@example.com', 'william@example.com', 'benjamin@example.com',
      'harper@example.com', 'sophia@example.com', 'ava@example.com', 'james@example.com'
    ];
    const phoneNumbers = [
      '123-456-7890', '234-567-8901', '345-678-9012', '456-789-0123',
      '567-890-1234', '678-901-2345', '789-012-3456', '890-123-4567',
      '901-234-5678', '012-345-6789', '123-456-7899', '234-567-8902',
      '345-678-9013', '456-789-0124', '567-890-1235', '678-901-2346',
      '789-012-3457', '890-123-4568', '901-234-5679', '012-345-6790',
      '123-456-7898', '234-567-8903', '345-678-9014', '456-789-0125',
      '567-890-2344', '678-901-3455', '789-012-4566', '890-123-5677',
      '901-234-6788', '012-345-7899', '123-456-8900', '234-567-9011',
      '345-678-0122', '456-789-1233', '567-890-2344', '678-901-3455',
      '789-012-4566', '890-123-5677', '901-234-6788', '012-345-7899',
      '123-456-7891', '234-567-8910', '345-678-0121', '456-789-1230',
      '567-890-2349', '678-901-3458', '789-012-4567', '890-123-5670',
      '901-234-6781', '012-345-7892', '123-456-8913', '234-567-9024',
      '345-678-0135', '456-789-1246', '567-890-2357', '678-901-3468',
      '789-012-4579', '890-123-5680', '901-234-6791', '012-345-7893',
      '123-457-7904', '234-568-9035', '345-679-0146', '456-790-1257',
      '567-891-2368', '678-902-3479', '789-013-4580', '890-124-5691',
      '901-235-6792', '012-346-7894', '123-458-7915', '234-569-9046',
      '345-680-0157', '456-791-1268', '567-892-2379', '678-903-3480',
      '789-014-4591', '890-125-5702', '901-236-6803', '012-347-8905',
      '123-459-7916', '234-570-9047', '345-681-0158', '456-792-1279',
      '567-893-2380', '678-904-3491', '789-015-4602', '890-126-5713',
      '901-237-6814', '012-348-8915', '123-460-7927', '234-571-9058',
      '345-682-0169', '456-793-1280', '567-894-2391', '678-905-3502',
      '789-016-4613', '890-127-5724', '901-238-6825', '012-349-8926'
    ];
  
    const locations = [
      'New York', 'Los Angeles', 'Chicago', 'Houston',
      'San Francisco', 'Austin', 'Seattle', 'Miami',
      'Boston', 'Dallas', 'Denver', 'Portland',
      'San Diego', 'Philadelphia', 'Minneapolis', 'Atlanta',
      'Phoenix', 'San Antonio', 'Las Vegas', 'Orlando',
      'Nashville', 'Columbus', 'New Orleans', 'Charlotte',
      'Indianapolis', 'Kansas City', 'Cincinnati', 'Pittsburgh',
      'Baltimore', 'Memphis', 'Raleigh', 'Cleveland',
      'Detroit', 'Sacramento', 'Salt Lake City', 'Oklahoma City',
      'Albany', 'Milwaukee', 'Fort Worth', 'Tampa',
      'El Paso', 'Omaha', 'Toledo', 'Reno',
      'Anchorage', 'Spokane', 'Wichita', 'Des Moines',
      'Bakersfield', 'Provo', 'Sioux Falls', 'Boise',
      'Las Cruces', 'Flagstaff', 'Charleston', 'Savannah',
      'St. Petersburg', 'Montgomery', 'Mobile', 'Pensacola',
      'Tucson', 'Tampa', 'Providence', 'Bridgeport',
      'Albany', 'Scranton', 'Santa Fe', 'Burlington',
      'Worcester', 'Hartford', 'Lancaster', 'Springfield',
      'Erie', 'Duluth', 'Fargo', 'Billings',
      'Rapid City', 'Bangor', 'Augusta', 'Cheyenne',
      'Bismarck', 'Helena', 'Casper', 'Missoula',
      'Laramie', 'Jackson', 'Grand Junction', 'Ketchikan',
      'Sitka', 'Nome', 'Fairbanks', 'Juneau',
      'Anchorage', 'Homer', 'Kodiak', 'Juno',
      'Ketchikan', 'Sitka', 'Fairbanks', 'Homer'
    ];
    const addresses = [
      '123 Main St', '456 Elm St', '789 Oak St', '321 Pine St',
      '1011 Maple Ave', '2022 Cedar Blvd', '3033 Birch Rd', '4044 Walnut St',
      '5055 Pine Dr', '6066 Spruce Ln', '7077 Willow Ct', '8088 Redwood Ter',
      '9099 Sycamore Way', '1100 Hickory Pl', '1111 Ash Cir', '2121 Cherry Rd',
      '3131 Beech Blvd', '4141 Alder Ave', '5151 Magnolia Ln', '6161 Fir Ct',
      '7171 Cypress St', '8181 Hazel Dr', '9191 Juniper Way', '1000 Cypress Blvd',
      '101 Maple Ct', '202 Cedar Ln', '303 Birch Pl', '404 Walnut St',
      '505 Pine Dr', '606 Spruce Ter', '707 Willow Ct', '808 Redwood Cir',
      '909 Sycamore Ave', '101 Hickory Ln', '111 Ash Blvd', '212 Cherry Ct',
      '313 Beech St', '414 Alder Dr', '515 Magnolia Way', '616 Fir Ave',
      '717 Cypress Blvd', '818 Hazel St', '919 Juniper Pl', '1001 Maple Ave',
      '1012 Cedar Ter', '2033 Birch Ct', '4044 Walnut Ln', '5055 Pine Cir',
      '6066 Spruce St', '7077 Willow Way', '8088 Redwood Blvd', '9099 Sycamore Ln',
      '1010 Hickory Way', '1111 Ash St', '2121 Cherry Pl', '3131 Beech Blvd',
      '4141 Alder Cir', '5151 Magnolia Way', '6161 Fir Ct', '7171 Cypress St',
      '8181 Hazel Ter', '9191 Juniper Way', '1002 Maple Ave', '2022 Cedar Ln',
      '3033 Birch Ct', '4044 Walnut Dr', '5055 Pine Way', '6066 Spruce Cir',
      '7077 Willow Ave', '8088 Redwood St', '9099 Sycamore Ter', '1100 Hickory Ct',
      '1111 Ash Pl', '2121 Cherry St', '3131 Beech Ter', '4141 Alder Way',
      '5151 Magnolia Ct', '6161 Fir Ave', '7171 Cypress Cir', '8181 Hazel Way',
      '9191 Juniper St', '1000 Cypress Cir', '1003 Maple St', '2023 Cedar Ave',
      '3034 Birch Blvd', '4045 Walnut Pl', '5056 Pine Ct', '6067 Spruce Way',
      '7078 Willow Ter', '8089 Redwood Ct', '9090 Sycamore St', '1101 Hickory Ave',
      '1112 Ash Cir', '2122 Cherry Way', '3132 Beech Ter', '4142 Alder Ln',
      '5152 Magnolia Ave', '6162 Fir Ct', '7172 Cypress St', '8182 Hazel Way',
      '9192 Juniper Cir', '1004 Cypress St'
    ];

    const birthdates = [
      '1985-03-15', '1992-07-22', '1978-11-30', '1988-06-19',
      '1991-12-05', '1980-05-15', '1993-09-20', '1977-02-14',
      '1984-08-07', '1996-04-12', '1990-10-17', '1979-03-21',
      '1995-01-27', '1983-07-10', '1994-11-23', '1991-02-28',
      '1986-06-05', '1975-12-17', '1989-09-03', '1982-08-11',
      '1993-10-15', '1987-05-30', '1976-07-22', '1992-04-05',
      '1988-09-18', '1985-01-29', '1977-06-13', '1994-03-06',
      '1993-05-21', '1982-12-07', '1996-08-29', '1983-02-10',
      '1981-09-11', '1992-05-26', '1975-08-16', '1997-03-05',
      '1986-11-19', '1998-04-12', '1991-09-15', '1987-07-20',
      '1984-03-08', '1995-05-31', '1976-02-24', '1989-10-07',
      '1987-01-14', '1990-08-02', '1979-05-04', '1996-11-20',
      '1981-06-27', '1995-12-17', '1977-10-30', '1986-01-02',
      '1989-03-12', '1975-08-23', '1997-06-07', '1993-11-29',
      '1987-04-17', '1994-07-10', '1995-01-01', '1985-12-21',
      '1976-09-09', '1990-04-27', '1992-02-12', '1981-10-05',
      '1989-07-15', '1993-02-20', '1978-06-06', '1983-08-31',
      '1995-10-01', '1979-09-30', '1992-03-04', '1994-01-25',
      '1985-11-14', '1983-03-15', '1991-04-22', '1996-07-28',
      '1998-08-11', '1984-06-18', '1980-10-29', '1976-02-08',
      '1991-11-27', '1987-03-08', '1993-01-15', '1985-04-12',
      '1980-08-25', '1986-04-02', '1977-11-06', '1997-05-14',
      '1990-07-23', '1989-02-25', '1983-04-03', '1998-03-19',
      '1975-10-13', '1991-06-09', '1987-08-02', '1984-12-26',
      '1992-08-17', '1994-09-11', '1985-10-31', '1988-01-08',
      '1997-12-14', '1981-03-03', '1993-12-25', '1983-11-19',
      '1987-11-07', '1985-07-06', '1991-08-28', '1980-01-16'
    ];

    const jobTitles = [
      'Software Engineer', 'Marketing Manager', 'Accountant', 'Graphic Designer',
      'Data Analyst', 'Teacher', 'Nurse', 'Web Developer',
      'Sales Associate', 'HR Specialist', 'Project Manager', 'Customer Service Rep',
      'Product Manager', 'Journalist', 'Electrical Engineer', 'Financial Advisor',
      'Architect', 'Chef', 'Attorney', 'Dentist',
      'Biochemist', 'UX Designer', 'Marketing Specialist', 'Event Planner',
      'Photographer', 'Statistician', 'Pilot', 'Interior Designer',
      'Cybersecurity Analyst', 'Agricultural Engineer', 'Supply Chain Manager',
      'Geologist', 'Logistics Coordinator', 'Technical Writer', 'Actuary',
      'Quality Control Inspector', 'Industrial Designer', 'Park Ranger',
      'Environmental Scientist', 'Veterinarian', 'Astronomer', 'Cost Estimator',
      'Biostatistician', 'Zoologist', 'Game Developer', 'Chemical Engineer',
      'Urban Planner', 'Environmental Engineer', 'Optometrist', 'Cultural Anthropologist',
      'Museum Curator', 'Biomedical Engineer', 'Epidemiologist', 'Culinary Arts Director',
      'Media Relations Specialist', 'Social Worker', 'Fire Protection Engineer',
      'Chemical Plant Operator', 'Greenhouse Manager', 'Library Archivist',
      'Systems Administrator', 'Political Analyst', 'Surgeon', 'Banker',
      'Psychiatrist', 'Audiologist', 'Toxicologist', 'Marine Biologist',
      'Physiologist', 'Mechanical Engineer', 'Sound Engineer', 'Orthodontist',
      'Industrial Hygienist', 'Archeologist', 'Microbiologist', 'Database Administrator',
      'Hotel Manager', 'Insurance Underwriter', 'Geotechnical Engineer', 'Mining Engineer',
      'Hydrologist', 'Landscape Architect', 'Cytogeneticist', 'Pathologist',
      'Kinesiologist', 'Forensic Analyst', 'Literary Agent', 'Travel Consultant',
      'Event Coordinator', 'Automotive Engineer', 'Phlebotomist', 'Meteorologist',
      'Investment Banker', 'Sculptor', 'Voice Actor', 'Sports Analyst',
      'Marine Engineer', 'Petroleum Geologist', 'Virtual Reality Developer',
      'Data Scientist', 'Fashion Designer', 'Radiologist', 'Logistician',
      'Substance Abuse Counselor', 'Robotics Engineer', 'Screenwriter', 'Cognitive Scientist',
      'Artificial Intelligence Engineer', 'Rehabilitation Counselor'
    ];

    const companyNames = [
      'Tech Innovators Inc.', 'Creative Horizons LLC', 'Health and Wellness Co.',
      'Digital Solutions Corp.', 'Sustainable Resources Ltd.', 'Apex Financial Group',
      'Quantum Enterprises', 'Bright Minds Consulting', 'Innovative Designs Inc.',
      'Cityscape Developments', 'Global Trade Ventures', 'Green Earth Corp.',
      'Eco Tech Solutions', 'Premier Marketing Group', 'Pioneer Engineering LLC',
      'Skyline Builders', 'Elite Education Services', 'Nutrient Naturals Co.',
      'Vanguard Investments', 'Star Media Productions', 'Advanced Logistics Group',
      'Future Vision Labs', 'Urban Architects LLC', 'Luxury Living Inc.',
      'Proactive Health Clinic', 'Master Craftsmen Ltd.', 'Cloud Nine Technology',
      'Harvest Moon Farms', 'Genesis Pharmaceuticals', 'Infinity Enterprises',
      'Momentum Energy Corp.', 'Galaxy Communications', 'Phoenix Manufacturing',
      'Aegis Security Systems', 'Digital Dreamscape Studios', 'Eagle Eye Surveillance',
      'Harmony Financial Services', 'Serenity Spa Retreat', 'Blue Ocean Cruises',
      'Pristine Legal Services', 'Epic Artistry Inc.', 'Silver Linings Insurance',
      'Harmony Electronics Inc.', 'Transcend Travel Agency', 'Elevation Real Estate',
      'Urban Gardens LLC', 'Sky High Construction', 'Regal Retreats Hotel Group',
      'Noble Healthcare Providers', 'Aqua Marine Yacht Club', 'Pioneer Publishing Co.',
      'Endless Horizons Travel Co.', 'Pinnacle Property Management', 'Vivid Imagery Studios',
      'Mindful Solutions Inc.', 'Oracle Outdoor Gear', 'Inspiring Spaces Interior Design',
      'Whispering Pines Winery', 'Empower Technology Corp.', 'The Happy Hiker Outdoors',
      'The Gourmet Palette Food Co.', 'Timeless Treasures Antiques', 'River Run Amusements',
      'Elite Equestrian Stable', 'Legacy Lumber Co.', 'Global Connections Travel',
      'Harmony Home Builders', 'Golden Grains Bakery', 'Prestige Luxury Autos',
      'Mystic Moonlight Candles', 'Dynamic Digital Media', 'Masterpiece Murals LLC',
      'Bright Beginnings Daycare', 'Majestic Mountains Retreat', 'Harmony Home Living',
      'White Sands Resort', 'The Golden Spoon Restaurant', 'The Wine Cellar',
      'The Garden Gate Florist', 'Metropolis Fitness Center', 'Golden Gate Productions',
      'The Artful Baker', 'Blue Sky Botanicals', 'Pinnacle Tech Solutions', 'Elite Fitness Studios',
      'Adventure Awaits Travel', 'Evergreen Landscaping', 'Urban Legends Apparel',
      'Meridian Motors', 'Rising Star Productions', 'Urban Roots Farm', 'Highland Hiking Co.',
      'Frosted Dreams Pastry Shop', 'Starry Night Entertainment', 'Coastal Cuisine Catering',
      'Tasty Treats Ice Cream', 'Sunrise Solar Solutions', 'Wholesome Herbs Co.'
    ];
    
    const hobbies = [
      'Reading', 'Hiking', 'Cooking', 'Photography', 'Traveling',
      'Gardening', 'Fishing', 'Painting', 'Cycling', 'Yoga',
      'Dancing', 'Skiing', 'Knitting', 'Playing Guitar', 'Sculpting',
      'Birdwatching', 'Pottery', 'Woodworking', 'Gardening', 'Origami',
      'Calligraphy', 'Brewing Beer', 'Soap Making', 'Tapestry',
      'Welding', 'Gemstone Polishing', 'Scrapbooking', 'Ceramics',
      'Magic Tricks', 'Beekeeping', 'Pilates', 'Salsa Dancing',
      'Quilting', 'Model Building', 'Windsurfing', 'Astronomy',
      'Kayaking', 'Jazz Singing', 'Metal Detecting', 'Juggling',
      'Basket Making', 'Rock Climbing', 'Wood Carving', 'Candle Making',
      'Herb Gardening', 'DIY Electronics', 'Wine Tasting', 'Genealogy',
      'Paragliding', 'Kite Flying', 'Chess', 'Cartoon Drawing',
      'Canoeing', 'Video Game Development', 'Metalworking', 'Gardening',
      'Embroidery', 'Fishkeeping', 'Writing Poetry', 'Board Games',
      'Mixed Martial Arts', 'Stand-up Comedy', 'Flower Arranging', 'Archery',
      'Video Editing', 'Sewing', 'Blacksmithing', 'Camping',
      'Surfing', 'Acting', 'Astrophotography', '3D Printing',
      'Film Making', 'Graphic Novels', 'Urban Exploration', 'Podcasting',
      'Glass Blowing', 'Puppetry', 'Soapstone Carving', 'Drumming',
      'Skateboarding', 'Tattoo Designing', 'Skincare Formulating',
      'Mountain Biking', 'Kombucha Brewing', 'Canning and Preserving',
      'Jewelry Making', 'Landscape Painting', 'Tea Tasting',
      'Live Streaming', 'Sailboat Racing', 'Whittling', 'Tattooing',
      'Playwriting', 'Horseback Riding', 'Fly Fishing', 'Bullet Journaling',
      'Violin Playing', 'Rug Weaving', 'Krav Maga', 'Hammock Camping',
      'Disc Golf', 'Stand-up Paddleboarding', 'Slacklining'
    ];

    const educationLevels = [
      "High School Diploma", "Bachelor's Degree", "Master's Degree",
      "Doctorate Degree", "Associate's Degree", "Technical Certificate",
      "Professional Diploma", "Post-Doctoral", "High School Equivalent",
      "Specialized Training", "Vocational Certificate", "Online Course Certification",
      "College Certificate", "GED", "Trade School Diploma",
      "Apprenticeship", "Professional Course", "Executive Education",
      "Seminar Completion", "Advanced Degree", "PhD Candidate",
      "Master of Business Administration", "Master of Science", "Master of Arts",
      "Bachelor of Science", "Bachelor of Arts", "Juris Doctor",
      "Medical Degree", "Master of Fine Arts", "Bachelor of Fine Arts",
      "Bachelor of Engineering", "Doctor of Engineering", "Doctor of Medicine",
      "Doctor of Dental Medicine", "Master of Public Health", "Master of Education",
      "Bachelor of Education", "Bachelor of Music", "Master of Music",
      "Master of Computer Science", "Bachelor of Computer Science",
      "Bachelor of Business Administration", "Master of Business Administration",
      "Master of Accounting", "Bachelor of Accounting", "Master of Finance",
      "Bachelor of Finance", "Master of Information Technology",
      "Bachelor of Information Technology", "Bachelor of Communications",
      "Master of Communications", "Bachelor of Economics", "Master of Economics",
      "Bachelor of Social Work", "Master of Social Work", "Master of Fine Arts",
      "Bachelor of Fine Arts", "Master of Journalism", "Bachelor of Journalism",
      "Bachelor of Psychology", "Master of Psychology", "Bachelor of Political Science",
      "Master of Political Science", "Bachelor of Law", "Master of Law",
      "Bachelor of Criminology", "Master of Criminology", "Bachelor of Science",
      "Master of Science", "Bachelor of Philosophy", "Master of Philosophy",
      "Bachelor of Arts", "Master of Arts", "Bachelor of Engineering",
      "Master of Engineering", "Bachelor of Medicine", "Master of Medicine",
      "Bachelor of Science in Nursing", "Master of Science in Nursing",
      "Bachelor of Science in Computer Science", "Master of Science in Computer Science",
      "Bachelor of Science in Business", "Master of Science in Business",
      "Bachelor of Science in Accounting", "Master of Science in Accounting",
      "Bachelor of Science in Finance", "Master of Science in Finance",
      "Bachelor of Science in Information Technology", "Master of Science in Information Technology",
      "Bachelor of Science in Communications", "Master of Science in Communications",
      "Bachelor of Science in Economics", "Master of Science in Economics",
      "Bachelor of Science in Social Work", "Master of Science in Social Work",
      "Bachelor of Fine Arts", "Master of Fine Arts", "Bachelor of Music",
      "Master of Music", "Bachelor of Architecture", "Master of Architecture",
      "Bachelor of Engineering", "Master of Engineering"
    ];
    
    const skills = [
      'Programming in Python', 'Programming in JavaScript', 'Programming in Java', 'Programming in C++',
      'Programming in Ruby', 'Programming in PHP', 'Programming in C#', 'Programming in Swift',
      'Mobile App Development', 'Web Development', 'Front-end Development', 'Back-end Development',
      'Full Stack Development', 'Database Management', 'SQL', 'Data Analysis',
      'Data Visualization', 'Machine Learning', 'Artificial Intelligence', 'Deep Learning',
      'Natural Language Processing', 'Cloud Computing', 'Cybersecurity', 'Network Administration',
      'IT Support', 'Systems Administration', 'DevOps', 'Agile Methodologies',
      'Project Management', 'Team Leadership', 'Product Management', 'Business Analysis',
      'Marketing Strategy', 'Digital Marketing', 'Search Engine Optimization (SEO)', 'Social Media Marketing',
      'Content Creation', 'Graphic Design', 'UI/UX Design', 'Video Editing',
      'Photography', 'Copywriting', 'Technical Writing', 'Public Speaking',
      'Sales Management', 'Negotiation', 'Customer Service', 'Account Management',
      'Event Planning', 'Financial Analysis', 'Accounting', 'Bookkeeping',
      'Tax Planning', 'Budgeting', 'Forecasting', 'Risk Management',
      'Auditing', 'Compliance Management', 'Supply Chain Management', 'Logistics',
      'Procurement', 'Quality Assurance', 'Human Resources Management', 'Recruitment',
      'Employee Relations', 'Training and Development', 'Organizational Development', 'Change Management',
      'Time Management', 'Problem-Solving', 'Critical Thinking', 'Creative Thinking',
      'Research', 'Data Collection', 'Data Interpretation', 'Data Entry',
      'Data Cleaning', 'Spreadsheet Analysis', 'Statistical Analysis', 'Presentation Skills',
      'Negotiation', 'Conflict Resolution', 'Contract Management', 'Legal Research',
      'Real Estate Management', 'Interior Design', 'Architecture', 'Engineering',
      'CAD Design', 'Drafting', 'Carpentry', 'Plumbing',
      'Electrical Work', 'Welding', 'HVAC', 'Mechanics',
      'Auto Repair', 'Machine Operation', 'Robotics', 'Electronics Repair',
      'Instrumentation', 'Surveying', 'Geospatial Analysis', 'Cartography',
      'Environmental Analysis', 'Biology Research', 'Chemistry Research', 'Physics Research',
      'Mathematics Research', 'Medical Research', 'Pharmaceuticals', 'Healthcare Management',
      'Nursing', 'Surgery', 'Anesthesia', 'Radiology'
    ];

    function getRandomSkills(skillsArray) {
      const selectedSkills = [];
      for (let i = 0; i < 3; i++) {
          const randomIndex = Math.floor(Math.random() * skillsArray.length);
          selectedSkills.push(skillsArray[randomIndex]);
      }
      return selectedSkills;
  }
  
  for (let i = 0; i < count; i++) {
      const user = {
        id: i + 1,
        name: names[i % names.length],
        email: emails[i % emails.length],
        phoneNumber: phoneNumbers[i % phoneNumbers.length],
        location: locations[i % locations.length],
        address: addresses[i % addresses.length],
        birthdate: birthdates[i % birthdates.length],
        jobTitle: jobTitles[i % jobTitles.length],
        companyName: companyNames[i % companyNames.length],
        hobbies: hobbies[i % hobbies.length],
        educationLevel: educationLevels[i % educationLevels.length],
        skills: getRandomSkills(skills)
      };
      users.push(user);
  }
  return users;
}